---
title: "In Context Presentation"
author: "Saloua Daouki"
date: "2023-11-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Shiny app to show the relationship between the students grades and their behavior


```{r }
# Loading the libraries
library(shiny)
library(ggplot2)
library(ggrepel)

# loading the dataset into R
URL <- 'https://raw.githubusercontent.com/SalouaDaouki/Data602/main/Students%20data.csv'
Data <- read.csv(file = URL)
# tidying the data
colnames(Data)[c(1, 6, 7, 8, 14)] = c("Student", "Mark1", "Mark2", "Mark3", "Behavior")
Data[Data == "#N/A"] <- NA
Data_cleaned  <- na.omit(Data)
Data_df <- data.frame(Data_cleaned)

# Define the UI
ui <- fluidPage(
  titlePanel("Student Performance and Behavior Analysis"),
  
  # Sidebar layout
  sidebarLayout(
    sidebarPanel(
      selectInput("behavior", "Select Behavior",
                  choices = c("Mark1", "Mark2", "Mark3", "Average", "Level"),
                  selected = "Behavior"),
    ),
    
    # Display thescatter plot
    mainPanel(
      plotOutput("scatterPlot"),
      tableOutput("filtered_data_table"),
    )
  )
)

# Define the server
server <- function(input, output) {
  # Create a reactive expression for the filtered data
  filteredData <- reactive({
    Data_df
  })
  
  # Render the scatter plot
  output$scatterPlot <- renderPlot({
    ggplot(filteredData(), aes(x = Behavior, y = filteredData()[[input$behavior]], label = Student)) +
      geom_point() +
      geom_text_repel() +
      theme(axis.text.x = element_text(angle = 45, hjust = 1))+
      labs(
        title = paste("Relationship between Behavior and", input$behavior),
        x = "Behavior",
        y = input$behavior
      )
  })
  # Render the filtered data table
  output$filtered_data_table <- renderTable({
    filteredData()
  })
}

# Run the Shiny app
shinyApp(ui = ui, server = server)
```

